name: 01 - Building Blocks

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello
              run: echo "Hello, World!"

    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Successful Step
              run: |
                echo "I am going to succeed now."
                exit 0
            - name: Goodbye Step
              if: ${{ always() }}
              run: echo "Goodbye, World!"